# Generated by Django 4.0.3 on 2023-07-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('detailing_type', models.CharField(max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('response', models.JSONField()),
            ],
        ),
    ]
