# Generated by Django 4.0.3 on 2023-07-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_detailing_type_weather_detailing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
